person:
  name: liuzhi
  age: 35
  email: dlxiaozh@hotmail.com
  happy: true
  birth: 2002/12/5
  maps: { k1: k,k2: 12 }
  lists:
        -adidas
        -nike
        -puma
  List: [zhangsan,lisi,wangwu]
  friends: {lastName: zhangsan,firstName: lz}